Omazan/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Omazan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Omazan.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket _basket;
        public CartSummaryViewComponent (Basket cartService)
        {
            _basket = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(_basket);
        }
    }
}

Omazan/Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Omazan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Omazan.Components
{
    public class CategoriesViewComponent : ViewComponent 
    {
        private IOmazanRepository _repo { get; set; }

        public CategoriesViewComponent (IOmazanRepository tmp)
        {
            _repo = tmp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.Selected = RouteData?.Values["category"];
            var categories = _repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Omazan/Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Books
 
<div class="container">
    <div class="row">
        <div class="col-6">
            <h2 style="color:cornflowerblue">@Model.Title</h2>
            <h5>@Model.Classification</h5>
            <small>@Model.Publisher (@Model.PageCount pages)</small>
            <br />
            <small>@Model.Isbn</small>
        </div>
        <div class="col-6 text-right d-flex flex-column justify-content-between">
            <h4>@Model.Author</h4>
            
            <h4 class="font-weight-bold">$@Model.Price</h4>
            <form method="post" asp-page="/Cart">
                <input type="hidden" asp-for="@Model.BookId" />
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
            </form>
        </div>
    </div>

</div>
<hr />

Omazan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bezos Books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="/lib/font-awesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bezos Books</a>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </nav>
    </header>
    <div class="container row m-2 p-1 pl-5 pr-5 mx-auto">
        <div class="col-3">
            <vc:categories></vc:categories>
        </div>
        <div class="col-9">
            
            @RenderBody()
            
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Omazan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>