Omazan/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Omazan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Omazan.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket _basket;
        public CartSummaryViewComponent (Basket cartService)
        {
            _basket = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(_basket);
        }
    }
}

Omazan/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Omazan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Omazan.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository _repo { get; set; }
        private Basket _basket { get; set; }
        public PurchaseController(IPurchaseRepository tmp, Basket basket)
        {
            _repo = tmp;
            _basket = basket;
        }


        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }
        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (_basket.items.Count() == 0)
            {
                ModelState.AddModelError("", "Your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = _basket.items.ToArray();
                _repo.SavePurchase(purchase);
                _basket.ClearBasket();

                return RedirectToPage("/Confirmation");
            } 
            else
            {
                return View();
            }
        }
    }
}

Omazan/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Omazan.Infrastructure;
using Omazan.Models;

namespace Omazan.Pages
{
    public class CartModel : PageModel
    {
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        private IOmazanRepository _repository { get; set; }

        public CartModel (IOmazanRepository tmp, Basket basket)
        {
            _repository = tmp;
            this.basket = basket;
        }


        

        public void OnGet(string returnUrl)
        {
            basket = HttpContext.Session.GetJson<Basket>("Basket") ?? new Basket();

            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int BookId, string returnUrl)
        {
            Books book = _repository.Books.FirstOrDefault(x => x.BookId == BookId);

            basket = HttpContext.Session.GetJson<Basket>("Basket") ?? new Basket();
            basket.AddItem(book, 1);

            HttpContext.Session.SetJson("Basket", basket);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
            
        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.items.FirstOrDefault(x => x.book.BookId == bookId).book);
            return RedirectToPage(new { ReturnUrl = returnUrl });

        }
    }
}

Omazan/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Omazan.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Omazan/Pages/Cart.cshtml
@page
@model Omazan.Pages.CartModel
@{
}


<h2>My Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.basket.items)
        {
            <tr>
                <td>@item.book.Title</td>
                <td>@item.quantity</td>
                <td>@item.book.Price.ToString("c")</td>
                <td>@((item.book.Price * item.quantity).ToString("c"))</td>
                <td class="text-center" style="width: 40px">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@item.book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-outline-danger">Remove</button>
                    </form>
                </td>
            </tr>

        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>@Model.basket.CalcTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table>
<div class="d-flex justify-content-between m-auto w-100">
    <a class="btn btn-outline-primary" href="@Model.ReturnUrl">&larr; Back</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Omazan/Pages/Confirmation.cshtml
@page
@model Omazan.Pages.ConfirmationModel
@{
}


<div class="m-auto text-center">
    <h1>Order Submitted!</h1>
    <hr />
    <br />
    <br />
    <a class="btn btn-outline-primary btn-lg" asp-controller="Home">Return to Home</a>
</div>

Omazan/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Omazan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bezos Books</a>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </nav>
    </header>
    <div class="container row m-2 p-1 pl-5 pr-5 mx-auto">
        @RenderBody()
    </div>
</body>
</html>